language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y
    - sudo apt-get update -qq
    
install: 
    - sudo apt-get -y install qt58base qt58declarative qt58svg
    - source /opt/qt58/bin/qt58-env.sh

script:
  - qmake PREFIX=/usr
  - make -j4
  - sudo make INSTALL_ROOT=appdir install ; sudo chown -R $USER appdir ; find appdir/
  - mkdir -p appdir/usr/bin ; cp ./switch.timsueberkrueb appdir/usr/bin
  - mkdir -p appdir/usr/share/applications/ ; cp click/switch.timsueberkrueb.desktop appdir/usr/share/applications/switch.desktop
  - mv appdir/switch.timsueberkrueb.desktop appdir/switch.desktop
  - mkdir -p appdir/usr/share/pixmaps/ ; mv appdir/icon.png appdir/usr/share/pixmaps/
  - rm appdir/*.apparmor || true
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" 
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage
  - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - curl --upload-file ./Switch*.AppImage https://transfer.sh/Switch-git.$(git rev-parse --short HEAD)-x86_64.AppImage
